FROM python:3.10 AS base

WORKDIR /app

# Setup env
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1

RUN pip install pipenv
RUN apt-get update && apt-get install -y --no-install-recommends gcc

COPY Pipfile .
COPY Pipfile.lock .

COPY ./services/traspaso_service/ ./services/traspaso_service/
COPY traspaso.py .

RUN pipenv install --system --deploy --ignore-pipfile

CMD ["sleep", "infinity"]
